---
# tasks file for InfluxDB
- name: Update Repositories
  become: yes
  apt:
    update_cache: yes

- name: Install Prerequisites
  become: yes
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - apt-transport-https

- name: Download and install influx-db key
  become: yes
  shell: wget -qO - https://repos.influxdata.com/influxdb.key | apt-key add -

- name: Add Influx-DB repository
  become: yes
  shell:  echo "deb https://repos.influxdata.com/ubuntu bionic stable" | tee /etc/apt/sources.list.d/influxdb.list

- name: Update the repositories
  become: yes
  apt:
    update_cache: yes

- name: Install influxdb influxdb-client telegraf kapacitor
  become: yes
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - influxdb
      - telegraf
      - kapacitor

- name: Download and install graphana key
  become: yes
  shell: wget -qO - https://packages.grafana.com/gpg.key | apt-key add -

- name: Add Graphana repository
  become: yes
  shell:  echo "deb https://packages.grafana.com/oss/deb stable main" | tee /etc/apt/sources.list.d/graphana.list

- name: Update the repositories
  become: yes
  apt:
    update_cache: yes

- name: Install graphana nginx
  become: yes
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - grafana
      - nginx

- name: Create influx automation directory
  become: yes
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - '/root/.influx_automate'

- name: Create Openssl req.conf File
  become: yes
  copy:
    src: req.conf
    dest: /root/.influx_automate/req.conf

- name: Set hostname in req.conf config file
  become: yes
  shell: sed -i s/XXXXX/$(hostname)/g /root/.influx_automate/req.conf

- name: Set ip address in req.conf config file
  become: yes
  shell: sed -i s/YYYYY/$(hostname -i | cut -d' ' -f1)/g /root/.influx_automate/req.conf

- name: Create nginx default config file
  become: yes
  copy:
    src: default.nginx
    dest: /root/.influx_automate/default

- name: Set hostname in nginx default config file
  become: yes
  shell: sed -i s/XXXXX/$(hostname)/g /root/.influx_automate/default

- name: Set ip address in nginx default config file
  become: yes
  shell: sed -i s/YYYYY/$(hostname -i | cut -d' ' -f1)/g /root/.influx_automate/default

- name: Upload nginx proxy initialization script
  become: yes
  copy:
    src: nginx_init.sh
    dest: /root/.influx_automate/nginx_init.sh

- name: Change permissions on nginx_init.sh
  become: yes
  file:
    path: /root/.influx_automate/nginx_init.sh
    mode: "u+rwx"
  ignore_errors: "{{ ansible_check_mode }}"

- name: Run Nginx Initialization script
  become: yes
  command: /root/.influx_automate/nginx_init.sh
  args:
    executable: /bin/bash
